export const TELEMETRY_THRESHOLDS = {
  AGGRESSIVE_MOVEMENT_G: 0.3,
  SHARP_TURN_G: 0.4,
  REQUIRED_CONSECUTIVE_TICKS: 5,
  COOLDOWN_MS: 3000,
} as const;

export const ENGINE_CONFIG = {
  POLLING_INTERVAL_MS: 80,
  LOW_PASS_FILTER_ALPHA: 0.8,
  BUFFER_SIZE: 10,
} as const;
